### ISSUE TITLE
Update ic-stable-structures to 0.6.x

### ISSUE THREAD

**Issue by lastmjs** [wasm-forge/ic-wasi-polyfill#14]
ic-stable-structures has gone through a major upgrade from 0.5.x to 0.6.x, removing the need to specify maximum key and value sizes. This has enormously positive developer experience benefits, and thus Azle upgraded a while ago.

I'm not trying to use the stable filesystem that the polyfill provides, while also providing our StableBTreeMap implementation. My understanding is that to ensure that polyfill's stable memory filesystem works well with stable structures, I need to use `init_with_memory` and pass in the memory used for my own stable structures.

I have tried to do this but it seems like the difficulties I am having arise from our stable structures being on 0.6.x and the polyfill's and/or stable-fs being on 0.5.x.

Can we get these versions updated? You might also be able to refactor your code now and remove maximum key and value sizes, I'm not sure if this has caused any trouble in the codebase.

**Comment by wasm-forge** [comment]
Hi Jordan,
I've updated the stable-structures to 0.6.2, should be working.

**Comment by lastmjs** [comment]
We will soon know if this works, thanks! Will reply and close if so
