### ISSUE TITLE
Stat returns true for all prefixes of a dirname

### ISSUE THREAD

**Issue by lastmjs** [wasm-forge/ic-wasi-polyfill#15]
I came across a bug in Azle while trying to create some directories and check for their existence. It seems like if a directory is created, then any prefix of that directory is returned with whatever the under-the-hood stat functionality is.

I've proved this with some very basic Rust code:

```rust
#[ic_cdk::init]
fn init() {
    ic_wasi_polyfill::init(&[], &[]);
}

#[ic_cdk::post_upgrade]
fn post_upgrade() {
    ic_wasi_polyfill::init(&[], &[]);
}

#[ic_cdk::update]
fn write() {
    std::fs::create_dir("public").unwrap();

    let pu_result = std::fs::metadata("pu").unwrap();

    ic_cdk::println!("pu_result: {:#?}", pu_result);

    let other_result = std::fs::metadata("other").unwrap();

    ic_cdk::println!("other_result: {:#?}", other_result);
}
```

The replica will print information for `pu_result` even though it does not exist, but it will panic on `other_result` as it should.

**Comment by wasm-forge** [comment]
Hello Jordan, the issue with file prefix should be sorted now in the latest version of stable-fs.

**Comment by lastmjs** [comment]
Has ic-wasi-polyfill been updated with this version?

**Comment by wasm-forge** [comment]
Yes, the ic-wasi-polyfill should peek up the latest working stable-fs that contains the fix.

**Comment by bdemann** [comment]
`let pu_result = std::fs::metadata("pu").unwrap();` panics as expected in version 0.5.0
