### ISSUE TITLE
read_dir always returns an empty set of entries

### ISSUE THREAD

**Issue by bdemann** [wasm-forge/ic-wasi-polyfill#16]
While I was working with [@lastmjs](https://github.com/lastmjs) on Azle I found that `readDirSync` was not working in the QuickJS interpreter compiled to wasm32-wasi. As we were looking into it we found that it uses `fd_readdir` in Wasi. The equivalent function in Rust is `read_dir`, and it also wasn't working (below I have a simple example demonstrating that). We are guessing that it also uses `fd_readdir` under the hood so we suspect that something is off with `fd_readdir`.

Here is my simple canister:
```rust
#[ic_cdk::init]
fn my_init() {
    ic_wasi_polyfill::init(&[], &[]);
}

#[ic_cdk::post_upgrade]
fn my_post_upgrade() {
    ic_wasi_polyfill::init(&[], &[]);
}

#[ic_cdk::query]
pub fn read_assets() -> String {
    let dir_name = "assets";
    std::fs::create_dir(dir_name).unwrap();
    std::fs::write(format!("{}/hello.txt", dir_name), "Hello").unwrap();
    std::fs::write(format!("{}/world.txt", dir_name), "World").unwrap();
    let entries = std::fs::read_dir(dir_name).unwrap();
    format!("Found {} files. Expected 2", entries.count())
}
```

I would expect there to be two files found when reading the 'assets' dir but it comes back with zero entries.

```bash
("Found 0 files. Expected 2")
```

**Comment by wasm-forge** [comment]
Hello Benjamin,
Thank you for your feedback! 
I am working on fixing the issue, it is almost done, but needs some more testing. 
I will let you know.

**Comment by wasm-forge** [comment]
Hello Benjamin,
The work with subfolders was improved, you can try out the latest ic-wasi-polyfill version 0.3.17.

**Comment by bdemann** [comment]
I just tested this out on version 0.5.0 and it works great!
