### ISSUE TITLE
create_dir_all fails if file already exists

### ISSUE THREAD

**Issue by wasm-forge** [wasm-forge/ic-wasi-polyfill#17]
In reference to [https://github.com/demergent-labs/azle/issues/1731]

### create_dir_all fails if file already exists
In src/compiler/rust/canister_methods/src/upload_file_chunk/write_chunk.rs we have a call to create_dir_all that most of the time behaves as expected. But when we do the manual upload test it fails on each chunk after the first, saying that the file already exists. Of course the file does in fact exist, but this function shouldn't fail in that case, and for all of our other chunked uploads it does not.

**Comment by bdemann** [comment]
After updating to version 0.5.0 and running our tests several times I haven't seen this issue come up any more

**Comment by wasm-forge** [comment]
Great to hear that!
