### ISSUE TITLE
stable-fs dependency incorrect

### ISSUE THREAD

**Issue by lastmjs** [wasm-forge/ic-wasi-polyfill#3]
Hey, I'm having some problems because of the way that the `stable-fs` dependency is written in the Cargo.toml:

```toml
stable-fs = { git = "https://github.com/wasm-forge/stable-fs", version = "0.1.8" }
```

I see you're trying to peg this to a specific version, but because you're pointing to a git repo, I don't think this really has any effect. It's going to pull from the latest commit of the master branch no matter what I'm pretty sure. What you want to do is set a `rev` with the hash of the code that you want this to point to.

I'm having a problem because I'm behind a bit with `ic-wasi-polyfill`, which is "pegged" to `0.1.5`, but in `0.1.8` you've changed some names of structs and such, and my code is now pulling that in. I can't patch it either it seems, because basically using `version` with `git` is either incorrect or not recommended, and my patch can't override it with a `rev`.

**Comment by wasm-forge** [comment]
I've increased the version number every time I've made some breaking change so that the `cargo` does not reuse some cached version of `stable-fs`. Thank you for the hint using `rev`!

**Comment by lastmjs** [comment]
Looks like this has been resolved, thanks!
