### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by lastmjs** [wasm-forge/ic-wasi-polyfill#7]
I noticed that `environ_get` and `environ_sizes_get` are both `no-op`. Is there a fundamental limitation that requires these be `no-op`?

It would be great to allow developers to pass environment variables into their canisters. We have implemented this functionality in Azle using a non-wasi custom implementation, where the developer specifies in their `dfx.json` which environment variables they would like passed over to the canister. We provide these environment variables in `process.env`.

I am looking to introduce this functionality into Kybra, and since Kybra is using Wasi, I would think it would be simple to implement this solution using `environ_get` and `environ_sizes_get` since the `os` module I believe would use these under-the-hood.

I would love to see these imports implemented.

**Comment by wasm-forge** [comment]
You can check the pull request:
https://github.com/wasm-forge/ic-wasi-polyfill/pull/8/files
